Vagrant.configure("2") do |config|

  # DB Server
  config.vm.define "DB_VM" do |db|
    db.vm.box = "ubuntu/focal64" # тут убунту 20.04,репозиторій можна змінити 
    db.vm.hostname = "db-server"
    db.vm.network "private_network", type: "dhcp"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1 
    end
    db.vm.provision "shell", path: "provision_db.sh"
  end

  # App Server
  config.vm.define "APP_VM" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.hostname = "app-server"
    app.vm.network "private_network", type: "dhcp"
    app.vm.network "forwarded_port", guest: 8080, host: 8080
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    app.vm.provision "shell", path: "provision_app.sh"
  end

end